### ISSUE TITLE
Getting exception during startup

### ISSUE THREAD

**Issue by oubiwann** [clojang/lfecljapp#13]
The initial command for starting the server no longer successfully completes. This isn't noticed if you use the LFE REPL (e.g., the `make dev` target). However, if you start from the command line, you'll see it:

```
Exception in thread "main" java.lang.NullPointerException
    at clojure.lang.Reflector.invokeInstanceMethod(Reflector.java:26)
    at cljnode.proto_handler$checkErlNode.invoke(proto_handler.clj:27)
    at cljnode.server$server.invoke(server.clj:32)
    at cljnode.core$_main.doInvoke(core.clj:20)
    at clojure.lang.RestFn.invoke(RestFn.java:397)
    at clojure.lang.AFn.applyToHelper(AFn.java:152)
    at clojure.lang.RestFn.applyTo(RestFn.java:132)
    at cljnode.core.main(Unknown Source)
```

**Comment by oubiwann** [comment]
Okay, I've isolated this as a system-specific issue, not a problem with ``lfecljapp`` per se. ``lfecljapp`` works just fine on my workstation (I get the error above on my laptop).

**Comment by oubiwann** [comment]
Not seeing this problem anymore.
